### ISSUE TITLE
Compressing empty input doesnt work

### ISSUE THREAD

**Issue by ghost** [NimCompression/nimsnappyc#1]
Everywhere where you used `input[0]` a check for `len == 0` is needed, so compressing empty input works too.

**Comment by data-man** [comment]
> compressing empty input 

What's the point of this?
Check your input before compressing.

**Comment by ghost** [comment]
Ok, I didn't want to compress empty input but sometimes the user input is empty.
But then I will do the check on my own.

**Comment by data-man** [comment]
Now returns the empty result.

Please let me know if this works for you.

**Comment by ghost** [comment]
Thanks! It works good for me. Maybe you can use `if unlikely(len == 0)` because I think it's quite rare that the input is empty.
